# Workflow will publish a Python package to PyPI when a new release is created

name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: uv build
      - run: uv publish --trusted-publishing always
